/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as PaycheckPlannerIndexImport } from './routes/paycheck-planner/index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PaycheckPlannerIndexRoute = PaycheckPlannerIndexImport.update({
  id: '/paycheck-planner/',
  path: '/paycheck-planner/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/paycheck-planner/': {
      id: '/paycheck-planner/'
      path: '/paycheck-planner'
      fullPath: '/paycheck-planner'
      preLoaderRoute: typeof PaycheckPlannerIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/paycheck-planner': typeof PaycheckPlannerIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/paycheck-planner': typeof PaycheckPlannerIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/paycheck-planner/': typeof PaycheckPlannerIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/paycheck-planner'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/paycheck-planner'
  id: '__root__' | '/' | '/paycheck-planner/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PaycheckPlannerIndexRoute: typeof PaycheckPlannerIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PaycheckPlannerIndexRoute: PaycheckPlannerIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/paycheck-planner/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/paycheck-planner/": {
      "filePath": "paycheck-planner/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
